+incdir+hw
+incdir+hw/ip/aes/rtl
+incdir+hw/ip/csrng/rtl
+incdir+hw/ip/edn/rtl
+incdir+hw/ip/entropy_src/rtl
+incdir+hw/ip/lc_ctrl/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/prim_generic/rtl
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey/rtl
+incdir+hw/workspace/opentitan/hw/ip/prim/rtl
hw/ip/prim/rtl/prim_assert.sv
hw/ip/aes/rtl/aes_pkg.sv
hw/ip/aes/rtl/aes_reg_pkg.sv
hw/ip/aes/rtl/aes_sbox_canright_pkg.sv
hw/ip/csrng/rtl/csrng_pkg.sv
hw/ip/csrng/rtl/csrng_reg_pkg.sv
hw/ip/edn/rtl/edn_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_edge_detector.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_mubi8_sync.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_arbiter_ppc.sv
hw/ip/csrng/rtl/csrng_core.sv
hw/ip/csrng/rtl/csrng_cmd_stage.sv
hw/ip/csrng/rtl/csrng_reg_top.sv
hw/ip/csrng/rtl/csrng_ctr_drbg.sv
hw/ip/csrng/rtl/csrng.sv
hw/ip/csrng/rtl/csrng_ctr_drbg_upd.sv
hw/ip/csrng/rtl/csrng_block_encrypt.sv
hw/ip/csrng/rtl/csrng_ctr_drbg_cmd.sv
hw/ip/csrng/rtl/csrng_main_sm.sv
hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv
hw/ip/csrng/rtl/csrng_state_db.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_buf.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_flop.sv
hw/ip/prim/rtl/prim_mubi4_sync.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_leading_one_ppc.sv
hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_flop_2sync.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
hw/ip/aes/rtl/aes_sbox.sv
hw/ip/aes/rtl/aes_sbox_dom.sv
hw/ip/aes/rtl/aes_shift_rows.sv
hw/ip/aes/rtl/aes_cipher_control_fsm.sv
hw/ip/aes/rtl/aes_sbox_canright.sv
hw/ip/aes/rtl/aes_sub_bytes.sv
hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
hw/ip/aes/rtl/aes_key_expand.sv
hw/ip/aes/rtl/aes_sbox_canright_masked.sv
hw/ip/aes/rtl/aes_sbox_lut.sv
hw/ip/aes/rtl/aes_mix_columns.sv
hw/ip/aes/rtl/aes_cipher_control.sv
hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
hw/ip/aes/rtl/aes_cipher_core.sv
hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
hw/ip/aes/rtl/aes_mix_single_column.sv
hw/ip/aes/rtl/aes_sel_buf_chk.sv
rtl_wrapper/csrng_perip_tb.sv
