+incdir+hw
+incdir+hw/hw
+incdir+hw/hw/ip
+incdir+hw/hw/ip/prim
+incdir+hw/hw/ip/prim/rtl
+incdir+hw/ip
+incdir+hw/ip/prim
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/tlul
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey
+incdir+hw/top_earlgrey/ip
+incdir+hw/top_earlgrey/ip/ast
+incdir+hw/top_earlgrey/ip/ast/rtl
+incdir+hw/top_earlgrey/rtl
hw/ip/prim/rtl/prim_assert.sv
hw/hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/top_earlgrey/rtl/top_racl_pkg.sv
hw/ip/prim/rtl/prim_flop_macros.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
rtl_wrapper/tlul_perip_tb.sv
