+incdir+hw
+incdir+hw/ip/aes/pre_dv/aes_cipher_core_tb/rtl
+incdir+hw/ip/aes/pre_dv/aes_sbox_lec
+incdir+hw/ip/aes/pre_dv/aes_sbox_tb/rtl
+incdir+hw/ip/aes/pre_dv/aes_wrap_tb/rtl
+incdir+hw/ip/aes/rtl
+incdir+hw/ip/csrng/rtl
+incdir+hw/ip/edn/rtl
+incdir+hw/ip/entropy_src/rtl
+incdir+hw/ip/keymgr/rtl
+incdir+hw/ip/lc_ctrl/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/prim_generic/rtl
+incdir+hw/ip/tlul/rtl
+incdir+hw/rtl
+incdir+hw/top_earlgrey/rtl
hw/ip/prim/rtl/prim_assert.sv
hw/ip/aes/rtl/prim_assert.sv
hw/ip/aes/rtl/aes_pkg.sv
hw/ip/aes/rtl/aes_reg_pkg.sv
hw/ip/aes/rtl/aes_sbox_canright_pkg.sv
hw/ip/csrng/rtl/csrng_pkg.sv
hw/ip/csrng/rtl/csrng_reg_pkg.sv
hw/ip/edn/rtl/edn_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_pkg.sv
hw/ip/keymgr/rtl/keymgr_pkg.sv
hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_cipher_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_esc_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim_generic/rtl/prim_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_sha2_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/prim/rtl/prim_trivium_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/rtl/top_pkg.sv
hw/ip/tlul/rtl/tlul_assert.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_socket_1n.sv
hw/ip/tlul/rtl/tlul_fifo_sync.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_adapter_sram.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err_resp.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_sram_byte.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_reg_cdc_arb.sv
hw/ip/prim/rtl/prim_lfsr.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_sha2_pad.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_reg_cdc.sv
hw/ip/prim/rtl/prim_packer.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_dom_and_2share.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_esc_receiver.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_sha2.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_trivium.sv
hw/ip/prim/rtl/prim_mubi4_sync.sv
hw/ip/prim/rtl/prim_slicer.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_sha2_32.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_mubi4_sender.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim_generic/rtl/prim_xor2.sv
hw/ip/prim_generic/rtl/prim_flop_en.sv
hw/ip/prim_generic/rtl/prim_and2.sv
hw/ip/prim_generic/rtl/prim_buf.sv
hw/ip/prim_generic/rtl/prim_flop.sv
hw/ip/prim_generic/rtl/prim_xnor2.sv
hw/ip/prim_generic/rtl/prim_clock_gating.sv
hw/ip/prim_generic/rtl/prim_flop_2sync.sv
hw/ip/aes/pre_dv/aes_wrap_tb/rtl/aes_wrap_tb.sv
hw/ip/aes/pre_dv/aes_cipher_core_tb/rtl/aes_cipher_core_tb.sv
hw/ip/aes/pre_dv/aes_sbox_lec/aes_sbox_masked_wrapper.sv
hw/ip/aes/pre_dv/aes_sbox_tb/rtl/aes_sbox_tb.sv
hw/ip/aes/rtl/aes_control_fsm_n.sv
hw/ip/aes/rtl/aes_ctr_fsm.sv
hw/ip/aes/rtl/aes_sbox.sv
hw/ip/aes/rtl/aes_sbox_dom.sv
hw/ip/aes/rtl/aes_shift_rows.sv
hw/ip/aes/rtl/aes_cipher_control_fsm.sv
hw/ip/aes/rtl/aes_sbox_canright.sv
hw/ip/aes/rtl/aes_sub_bytes.sv
hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
hw/ip/aes/rtl/aes_control_fsm.sv
hw/ip/aes/rtl/aes_reg_top.sv
hw/ip/aes/rtl/aes_ctrl_reg_shadowed.sv
hw/ip/aes/rtl/aes_key_expand.sv
hw/ip/aes/rtl/aes_ctr_fsm_n.sv
hw/ip/aes/rtl/aes.sv
hw/ip/aes/rtl/aes_sbox_canright_masked.sv
hw/ip/aes/rtl/aes_reg_status.sv
hw/ip/aes/rtl/aes_core.sv
hw/ip/aes/rtl/aes_sbox_lut.sv
hw/ip/aes/rtl/aes_mix_columns.sv
hw/ip/aes/rtl/aes_ctr.sv
hw/ip/aes/rtl/aes_cipher_control.sv
hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
hw/ip/aes/rtl/aes_cipher_core.sv
hw/ip/aes/rtl/aes_ctr_fsm_p.sv
hw/ip/aes/rtl/aes_control.sv
hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
hw/ip/aes/rtl/aes_reduced_round.sv
hw/ip/aes/rtl/aes_control_fsm_p.sv
hw/ip/aes/rtl/aes_wrap.sv
hw/ip/aes/rtl/aes_mix_single_column.sv
hw/ip/aes/rtl/aes_prng_masking.sv
hw/ip/aes/rtl/aes_sel_buf_chk.sv
hw/ip/aes/rtl/aes_prng_clearing.sv
hw/ip/aes/rtl/aes_ctrl_gcm_reg_shadowed.sv
hw/ip/aes/rtl/aes_ghash.sv
hw/ip/prim/rtl/prim_blanker.sv
hw/ip/prim/rtl/prim_onehot_mux.sv
hw/ip/prim/rtl/prim_gf_mult.sv
rtl_wrapper/aes_perip_tb.sv
