+incdir+hw/pulp_riscv_dbg/src
+incdir+hw/prim/rtl
hw/prim/rtl/prim_util_pkg.sv
hw/prim/rtl/prim_assert.sv
hw/prim/rtl/prim_secded_pkg.sv
hw/prim/rtl/prim_flop_macros.sv
hw/prim/rtl/prim_generic_flop.sv
hw/prim/rtl/prim_flop.sv
hw/prim/rtl/prim_sync_reqack.sv
hw/prim/rtl/prim_flop_2sync.sv
hw/prim/rtl/prim_clock_inv.sv
hw/prim/rtl/prim_clock_mux2.sv
hw/prim/rtl/prim_fifo_sync_cnt.sv
hw/prim/rtl/prim_fifo_sync.sv
hw/prim/rtl/prim_fifo_async_simple.sv
hw/prim/rtl/prim_sparse_fsm_flop.sv
hw/prim/rtl/prim_subreg_pkg.sv
hw/prim/rtl/prim_subreg.sv
hw/debug_rom/debug_rom.sv
hw/pulp_riscv_dbg/src/dm_pkg.sv
hw/pulp_riscv_dbg/src/dmi_cdc.sv
hw/pulp_riscv_dbg/src/dmi_jtag_tap.sv
hw/pulp_riscv_dbg/src/dmi_jtag.sv
hw/pulp_riscv_dbg/src/dm_csrs.sv
hw/pulp_riscv_dbg/src/dm_mem.sv
hw/pulp_riscv_dbg/src/dm_sba.sv
hw/pulp_riscv_dbg/src/dm_top.sv
rtl_wrapper/rv_dm_perip_tb.sv
