+incdir+hw/ip/prim/rtl
hw/ip/clkmgr/rtl/clkmgr_reg_pkg.sv
hw/ip/clkmgr/rtl/clkmgr_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_reg_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_assert.sv
hw/ip/prim/rtl/prim_cipher_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_flop_macros.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_sha2_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/prim_generic/rtl/prim_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/top_pkg.sv
hw/top_earlgrey/top_racl_pkg.sv
hw/ip/clkmgr/rtl/clkmgr.sv
hw/ip/clkmgr/rtl/clkmgr_byp.sv
hw/ip/clkmgr/rtl/clkmgr_clk_status.sv
hw/ip/clkmgr/rtl/clkmgr_meas_chk.sv
hw/ip/clkmgr/rtl/clkmgr_root_ctrl.sv
hw/ip/clkmgr/rtl/clkmgr_trans.sv
hw/ip/clkmgr/rtl/clkmgr_reg_top.sv
hw/ip/prim/rtl/prim_ram_1p_adv.sv
hw/ip/prim/rtl/prim_secded_39_32_enc.sv
hw/ip/prim/rtl/prim_secded_39_32_dec.sv
hw/ip/prim/rtl/prim_secded_72_64_enc.sv
hw/ip/prim/rtl/prim_secded_72_64_dec.sv
hw/ip/prim/rtl/prim_arbiter_ppc.sv
hw/ip/prim/rtl/prim_arbiter_fixed.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_reg_cdc.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_packer.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_sha2_32.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_clock_buf.sv
hw/ip/prim/rtl/prim_clock_gating_sync.sv
hw/ip/prim/rtl/prim_edge_detector.sv
hw/ip/prim_generic/rtl/prim_clock_div.sv
hw/ip/prim/rtl/prim_xor2.sv
hw/ip/prim_generic/rtl/prim_clock_mux2.sv
hw/ip/prim_generic/rtl/prim_clock_inv.sv
hw/ip/prim_generic/rtl/prim_buf.sv
hw/ip/prim_generic/rtl/prim_flop.sv
hw/ip/prim_generic/rtl/prim_flop_2sync.sv
hw/ip/prim_generic/rtl/prim_clock_gating.sv
hw/ip/tlul/rtl/tlul_assert.sv
hw/ip/tlul/rtl/tlul_assert_multiple.sv
hw/ip/tlul/rtl/tlul_fifo_sync.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_socket_1n.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_err_resp.sv
rtl_wrapper/clkmgr_perip_tb.sv
