+incdir+hw/ip/prim/rtl
hw/ip/prim_generic/rtl/prim_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim/rtl/prim_assert.sv
hw/ip/prim/rtl/prim_flop_macros.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/prim/rtl/prim_cipher_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_esc_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_sha2_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_2p_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/top_pkg.sv
hw/top_earlgrey/top_racl_pkg.sv
hw/top_earlgrey/jtag_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_pkg.sv
hw/ip/csrng/rtl/csrng_pkg.sv
hw/ip/edn/rtl/edn_pkg.sv
hw/ip/ast/rtl/ast_pkg.sv
hw/ip/otp_macro/rtl/otp_macro_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_macro_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_reg_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_top_specific_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_part_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_reg_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
hw/ip/flash_ctrl/rtl/flash_phy_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_top_specific_pkg.sv
+incdir+hw/ip/prim/rtl
hw/ip/flash_ctrl/rtl/flash_ctrl.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_mem_reg_top.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_prim_reg_top.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_arb.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_erase.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_info_cfg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_prog.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_rd.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_region_cfg.sv
hw/ip/flash_ctrl/rtl/flash_mp.sv
hw/ip/flash_ctrl/rtl/flash_mp_data_region_sel.sv
hw/ip/flash_ctrl/rtl/flash_phy.sv
hw/ip/flash_ctrl/rtl/flash_phy_core.sv
hw/ip/flash_ctrl/rtl/flash_phy_erase.sv
hw/ip/flash_ctrl/rtl/flash_phy_prog.sv
hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
hw/ip/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv
hw/ip/flash_ctrl/rtl/flash_phy_rd_buffers.sv
hw/ip/flash_ctrl/rtl/flash_phy_scramble.sv
hw/top_earlgrey/rtl/otp_ctrl_dai.sv
hw/top_earlgrey/rtl/otp_ctrl_ecc_reg.sv
hw/top_earlgrey/rtl/otp_ctrl_kdi.sv
hw/top_earlgrey/rtl/otp_ctrl_lci.sv
hw/top_earlgrey/rtl/otp_ctrl_lfsr_timer.sv
hw/top_earlgrey/rtl/otp_ctrl_part_buf.sv
hw/top_earlgrey/rtl/otp_ctrl_part_unbuf.sv
hw/top_earlgrey/rtl/otp_ctrl_scrmbl.sv
hw/top_earlgrey/rtl/otp_ctrl_token_const.sv
hw/ip/prim/rtl/prim_ram_1p_adv.sv
hw/ip/prim/rtl/prim_secded_39_32_enc.sv
hw/ip/prim/rtl/prim_secded_39_32_dec.sv
hw/ip/prim/rtl/prim_secded_72_64_enc.sv
hw/ip/prim/rtl/prim_secded_72_64_dec.sv
hw/ip/prim/rtl/prim_arbiter_ppc.sv
hw/ip/prim/rtl/prim_arbiter_fixed.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_reg_cdc.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_alert_receiver.sv
hw/ip/prim/rtl/prim_esc_sender.sv
hw/ip/prim/rtl/prim_esc_receiver.sv
hw/ip/prim/rtl/prim_packer.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_sha2_32.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_lfsr.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_edge_detector.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_onehot_enc.sv
hw/ip/prim/rtl/prim_onehot_mux.sv
hw/ip/prim/rtl/prim_max_tree.sv
hw/ip/prim/rtl/prim_sum_tree.sv
hw/ip/prim/rtl/prim_leading_one_ppc.sv
hw/ip/prim/rtl/prim_msb_extend.sv
hw/ip/prim/rtl/prim_slicer.sv
hw/ip/prim/rtl/prim_blanker.sv
hw/ip/prim/rtl/prim_xoshiro256pp.sv
hw/ip/prim/rtl/prim_dom_and_2share.sv
hw/ip/prim/rtl/prim_sync_slow_fast.sv
hw/ip/prim/rtl/prim_pulse_sync.sv
hw/ip/prim/rtl/prim_cdc_rand_delay.sv
hw/ip/prim/rtl/prim_ram_1p_scr.sv
hw/ip/prim/rtl/prim_ram_1r1w_adv.sv
hw/ip/prim/rtl/prim_ram_2p_adv.sv
hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
hw/ip/prim/rtl/prim_fifo_async.sv
hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_filter.sv
hw/ip/prim/rtl/prim_filter_ctr.sv
hw/ip/prim/rtl/prim_clock_meas.sv
hw/ip/prim/rtl/prim_clock_timeout.sv
hw/ip/prim/rtl/prim_clock_gating_sync.sv
hw/ip/prim/rtl/prim_lc_and_hardened.sv
hw/ip/prim/rtl/prim_lc_or_hardened.sv
hw/ip/prim/rtl/prim_lc_combine.sv
hw/ip/prim/rtl/prim_lc_dec.sv
hw/ip/prim/rtl/prim_lc_sender.sv
hw/ip/prim/rtl/prim_multibit_sync.sv
hw/ip/prim/rtl/prim_double_lfsr.sv
hw/ip/prim/rtl/prim_gf_mult.sv
hw/ip/prim/rtl/prim_present.sv
hw/ip/prim/rtl/prim_prince.sv
hw/ip/prim/rtl/prim_subst_perm.sv
hw/ip/prim/rtl/prim_crc32.sv
hw/ip/prim/rtl/prim_edn_req.sv
hw/ip/prim/rtl/prim_rst_sync.sv
hw/ip/prim_generic/rtl/prim_buf.sv
hw/ip/prim_generic/rtl/prim_flop.sv
hw/ip/prim_generic/rtl/prim_flop_2sync.sv
hw/ip/prim_generic/rtl/prim_clock_gating.sv
hw/ip/prim_generic/rtl/prim_xnor2.sv
hw/ip/prim_generic/rtl/prim_xor2.sv
hw/ip/prim_generic/rtl/prim_and2.sv
hw/ip/prim_generic/rtl/prim_or2.sv
hw/ip/prim_generic/rtl/prim_flash.sv
hw/ip/prim_generic/rtl/prim_flash_bank.sv
hw/ip/prim_generic/rtl/prim_ram_1p.sv
hw/ip/tlul/rtl/tlul_assert.sv
hw/ip/tlul/rtl/tlul_assert_multiple.sv
hw/ip/tlul/rtl/tlul_fifo_sync.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_socket_1n.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_err_resp.sv
hw/ip/tlul/rtl/tlul_sram_byte.sv
hw/ip/tlul/rtl/tlul_lc_gate.sv
hw/ip/tlul/rtl/tlul_adapter_sram.sv
hw/ip/tlul/rtl/sram2tlul.sv
rtl_wrapper/flash_ctrl_perip_tb.sv
