+incdir+hw
+incdir+hw/ip/ast/rtl
+incdir+hw/ip/csrng/rtl
+incdir+hw/ip/edn/rtl
+incdir+hw/ip/entropy_src/rtl
+incdir+hw/ip/flash_ctrl/rtl
+incdir+hw/ip/keymgr/rtl
+incdir+hw/ip/lc_ctrl/rtl
+incdir+hw/ip/otbn/rtl
+incdir+hw/ip/otp_macro/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/prim_generic/rtl
+incdir+hw/ip/pwrmgr/rtl
+incdir+hw/ip/sram_ctrl/rtl
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey
+incdir+hw/top_earlgrey/rtl
hw/ip/prim/rtl/prim_assert.sv
hw/ip/edn/rtl/prim_assert.sv
hw/ip/lc_ctrl/rtl/prim_assert.sv
hw/top_earlgrey/rtl/alert_handler_pkg.sv
hw/top_earlgrey/rtl/alert_handler_reg_pkg.sv
hw/ip/ast/rtl/ast_pkg.sv
hw/ip/csrng/rtl/csrng_pkg.sv
hw/ip/csrng/rtl/csrng_reg_pkg.sv
hw/ip/edn/rtl/edn_pkg.sv
hw/ip/edn/rtl/edn_reg_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_ack_sm_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_main_sm_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_top_specific_pkg.sv
hw/ip/flash_ctrl/rtl/flash_phy_pkg.sv
hw/top_earlgrey/jtag_pkg.sv
hw/ip/keymgr/rtl/keymgr_pkg.sv
hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/otbn/rtl/otbn_pkg.sv
hw/ip/otbn/rtl/otbn_reg_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_macro_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_reg_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_top_specific_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_part_pkg.sv
hw/ip/otp_macro/rtl/otp_macro_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_ascon_pkg.sv
hw/ip/prim/rtl/prim_cipher_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_esc_pkg.sv
hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv
hw/ip/prim_generic/rtl/prim_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_2p_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_sha2_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/prim/rtl/prim_trivium_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_reg_pkg.sv
hw/ip/sram_ctrl/rtl/sram_ctrl_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/top_pkg.sv
hw/top_earlgrey/top_racl_pkg.sv
hw/top_earlgrey/rtl/otp_ctrl_scrmbl.sv
hw/top_earlgrey/rtl/otp_ctrl_part_buf.sv
hw/top_earlgrey/rtl/otp_ctrl_dai.sv
hw/top_earlgrey/rtl/otp_ctrl_core_reg_top.sv
hw/top_earlgrey/rtl/alert_handler_reg_wrap.sv
hw/top_earlgrey/rtl/otp_ctrl.sv
hw/top_earlgrey/rtl/otp_ctrl_part_unbuf.sv
hw/top_earlgrey/rtl/alert_handler_class.sv
hw/top_earlgrey/rtl/alert_handler.sv
hw/top_earlgrey/rtl/otp_ctrl_lci.sv
hw/top_earlgrey/rtl/alert_handler_ping_timer.sv
hw/top_earlgrey/rtl/otp_ctrl_kdi.sv
hw/top_earlgrey/rtl/otp_ctrl_ecc_reg.sv
hw/top_earlgrey/rtl/alert_handler_esc_timer.sv
hw/top_earlgrey/rtl/alert_handler_accu.sv
hw/top_earlgrey/rtl/alert_handler_lpg_ctrl.sv
hw/top_earlgrey/rtl/otp_ctrl_token_const.sv
hw/top_earlgrey/rtl/otp_ctrl_lfsr_timer.sv
hw/top_earlgrey/rtl/alert_handler_reg_top.sv
hw/ip/edn/rtl/edn_ack_sm.sv
hw/ip/edn/rtl/edn_reg_top.sv
hw/ip/edn/rtl/edn_field_en.sv
hw/ip/edn/rtl/edn_main_sm.sv
hw/ip/edn/rtl/edn_core.sv
hw/ip/edn/rtl/edn.sv
hw/ip/csrng/rtl/csrng_core.sv
hw/ip/csrng/rtl/csrng_cmd_stage.sv
hw/ip/csrng/rtl/csrng_reg_top.sv
hw/ip/csrng/rtl/csrng.sv
hw/ip/csrng/rtl/csrng_ctr_drbg_upd.sv
hw/ip/csrng/rtl/csrng_block_encrypt.sv
hw/ip/csrng/rtl/csrng_ctr_drbg_cmd.sv
hw/ip/csrng/rtl/csrng_main_sm.sv
hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv
hw/ip/csrng/rtl/csrng_state_db.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_prim_reg_top.sv
hw/ip/flash_ctrl/rtl/flash_phy_rd_buffers.sv
hw/ip/flash_ctrl/rtl/flash_phy_prog.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_prog.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_arb.sv
hw/ip/flash_ctrl/rtl/flash_phy_scramble.sv
hw/ip/flash_ctrl/rtl/flash_phy_core.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_mem_reg_top.sv
hw/ip/flash_ctrl/rtl/flash_mp_data_region_sel.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv
hw/ip/flash_ctrl/rtl/flash_phy.sv
hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
hw/ip/flash_ctrl/rtl/flash_phy_erase.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_region_cfg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_info_cfg.sv
hw/ip/flash_ctrl/rtl/flash_mp.sv
hw/ip/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_rd.sv
hw/ip/flash_ctrl/rtl/flash_ctrl.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_erase.sv
hw/ip/tlul/rtl/tlul_jtag_dtm.sv
hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
hw/ip/tlul/rtl/tlul_assert_multiple.sv
hw/ip/tlul/rtl/tlul_adapter_host.sv
hw/ip/tlul/rtl/tlul_assert.sv
hw/ip/tlul/rtl/sram2tlul.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_socket_1n.sv
hw/ip/tlul/rtl/tlul_adapter_dmi.sv
hw/ip/tlul/rtl/tlul_lc_gate.sv
hw/ip/tlul/rtl/tlul_fifo_sync.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_fifo_async.sv
hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv
hw/ip/tlul/rtl/tlul_socket_m1.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_adapter_sram.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err_resp.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_adapter_racl.sv
hw/ip/tlul/rtl/tlul_request_loopback.sv
hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv
hw/ip/tlul/rtl/tlul_sram_byte.sv
hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv
hw/ip/lc_ctrl/rtl/lc_ctrl.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_dmi_reg_top.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_regs_reg_top.sv
hw/ip/otbn/rtl/otbn.sv
hw/ip/otbn/rtl/otbn_rf_bignum_ff.sv
hw/ip/otbn/rtl/otbn_rf_base.sv
hw/ip/otbn/rtl/otbn_lsu.sv
hw/ip/otbn/rtl/otbn_rnd.sv
hw/ip/otbn/rtl/otbn_mac_bignum.sv
hw/ip/otbn/rtl/otbn_start_stop_control.sv
hw/ip/otbn/rtl/otbn_controller.sv
hw/ip/otbn/rtl/otbn_reg_top.sv
hw/ip/otbn/rtl/otbn_rf_bignum.sv
hw/ip/otbn/rtl/otbn_core.sv
hw/ip/otbn/rtl/otbn_rf_bignum_fpga.sv
hw/ip/otbn/rtl/otbn_decoder.sv
hw/ip/otbn/rtl/otbn_loop_controller.sv
hw/ip/otbn/rtl/otbn_instruction_fetch.sv
hw/ip/otbn/rtl/otbn_rf_base_ff.sv
hw/ip/otbn/rtl/otbn_stack.sv
hw/ip/otbn/rtl/otbn_alu_bignum.sv
hw/ip/otbn/rtl/otbn_predecode.sv
hw/ip/otbn/rtl/otbn_scramble_ctrl.sv
hw/ip/otbn/rtl/otbn_rf_base_fpga.sv
hw/ip/otbn/rtl/otbn_alu_base.sv
hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv
hw/ip/entropy_src/rtl/entropy_src_core.sv
hw/ip/entropy_src/rtl/entropy_src_enable_delay.sv
hw/ip/entropy_src/rtl/entropy_src_watermark_reg.sv
hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv
hw/ip/entropy_src/rtl/entropy_src.sv
hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv
hw/ip/entropy_src/rtl/entropy_src_cntr_reg.sv
hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv
hw/ip/entropy_src/rtl/entropy_src_repcnts_ht.sv
hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv
hw/ip/entropy_src/rtl/entropy_src_field_en.sv
hw/ip/prim/rtl/prim_pulse_sync.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_secded_28_22_dec.sv
hw/ip/prim/rtl/prim_cdc_rand_delay.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_edge_detector.sv
hw/ip/prim/rtl/prim_reg_cdc_arb.sv
hw/ip/prim/rtl/prim_diff_to_alert.sv
hw/ip/prim/rtl/prim_subst_perm.sv
hw/ip/prim/rtl/prim_crc32.sv
hw/ip/prim/rtl/prim_blanker.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv
hw/ip/prim/rtl/prim_clock_timeout.sv
hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
hw/ip/prim/rtl/prim_mubi4_dec.sv
hw/ip/prim/rtl/prim_racl_error_arb.sv
hw/ip/prim/rtl/prim_mubi8_dec.sv
hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv
hw/ip/prim/rtl/prim_mubi28_dec.sv
hw/ip/prim_generic/rtl/prim_rom_pkg.sv
hw/ip/prim/rtl/prim_rom_adv.sv
hw/ip/prim/rtl/prim_mubi24_sender.sv
hw/ip/prim/rtl/prim_mubi24_dec.sv
hw/ip/prim/rtl/prim_mubi12_dec.sv
hw/ip/prim/rtl/prim_mubi8_sync.sv
hw/ip/prim/rtl/prim_mubi32_sync.sv
hw/ip/prim/rtl/prim_lfsr.sv
hw/ip/prim/rtl/prim_arbiter_ppc.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
hw/ip/prim/rtl/prim_secded_39_32_enc.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_ram_2p_adv.sv
hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
hw/ip/prim/rtl/prim_secded_72_64_enc.sv
hw/ip/prim/rtl/prim_keccak.sv
hw/ip/prim/rtl/prim_ram_1p_scr.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_sha2_pad.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_mubi16_sender.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_alert_receiver.sv
hw/ip/prim/rtl/prim_mubi16_dec.sv
hw/ip/prim/rtl/prim_secded_22_16_dec.sv
hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
hw/ip/prim/rtl/prim_reg_cdc.sv
hw/ip/prim/rtl/prim_mubi20_dec.sv
hw/ip/prim/rtl/prim_secded_64_57_enc.sv
hw/ip/prim/rtl/prim_mubi32_dec.sv
hw/ip/prim/rtl/prim_clock_meas.sv
hw/ip/prim/rtl/prim_mubi20_sync.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv
hw/ip/prim/rtl/prim_mubi16_sync.sv
hw/ip/prim/rtl/prim_clock_gating_sync.sv
hw/ip/prim/rtl/prim_lc_dec.sv
hw/ip/prim/rtl/prim_packer.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
hw/ip/prim/rtl/prim_onehot_mux.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_ascon_sbox.sv
hw/ip/prim/rtl/prim_ram_1p_adv.sv
hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_mubi28_sync.sv
hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
hw/ip/prim/rtl/prim_dom_and_2share.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_mubi28_sender.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
hw/ip/prim/rtl/prim_fifo_async_simple.sv
hw/ip/prim/rtl/prim_msb_extend.sv
hw/ip/prim/rtl/prim_esc_receiver.sv
hw/ip/prim/rtl/prim_rst_sync.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_arbiter_tree_dup.sv
hw/ip/prim/rtl/prim_lc_and_hardened.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_xoshiro256pp.sv
hw/ip/prim/rtl/prim_mubi24_sync.sv
hw/ip/prim/rtl/prim_lc_combine.sv
hw/ip/prim/rtl/prim_filter_ctr.sv
hw/ip/prim/rtl/prim_sram_arbiter.sv
hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
hw/ip/prim/rtl/prim_gate_gen.sv
hw/ip/prim/rtl/prim_mubi20_sender.sv
hw/ip/prim/rtl/prim_ram_1r1w_adv.sv
hw/ip/prim/rtl/prim_diff_encode.sv
hw/ip/prim/rtl/prim_ascon_duplex.sv
hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_arbiter_fixed.sv
hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
hw/ip/prim/rtl/prim_double_lfsr.sv
hw/ip/prim/rtl/prim_filter.sv
hw/ip/prim/rtl/prim_gf_mult.sv
hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
hw/ip/prim/rtl/prim_mubi12_sync.sv
hw/ip/prim/rtl/prim_sha2.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_sum_tree.sv
hw/ip/prim/rtl/prim_alert_to_diff.sv
hw/ip/prim/rtl/prim_present.sv
hw/ip/prim/rtl/prim_secded_22_16_enc.sv
hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
hw/ip/prim/rtl/prim_ram_1r1w_async_adv.sv
hw/ip/prim/rtl/prim_mubi32_sender.sv
hw/ip/prim/rtl/prim_secded_64_57_dec.sv
hw/ip/prim/rtl/prim_prince.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_ascon_round.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
hw/ip/prim/rtl/prim_max_tree.sv
hw/ip/prim/rtl/prim_mubi8_sender.sv
hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv
hw/ip/prim/rtl/prim_multibit_sync.sv
hw/ip/prim/rtl/prim_edn_req.sv
hw/ip/prim/rtl/prim_trivium.sv
hw/ip/prim/rtl/prim_mubi4_sync.sv
hw/ip/prim/rtl/prim_fifo_async.sv
hw/ip/prim/rtl/prim_slicer.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_leading_one_ppc.sv
hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim/rtl/prim_onehot_enc.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
hw/ip/prim/rtl/prim_secded_39_32_dec.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
hw/ip/prim/rtl/prim_sha2_32.sv
hw/ip/prim/rtl/prim_secded_72_64_dec.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_lc_sender.sv
hw/ip/prim/rtl/prim_esc_sender.sv
hw/ip/prim/rtl/prim_lc_or_hardened.sv
hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
hw/ip/prim/rtl/prim_secded_28_22_enc.sv
hw/ip/prim/rtl/prim_mubi12_sender.sv
hw/ip/prim/rtl/prim_arbiter_tree.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_mubi4_sender.sv
hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv
hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_sync_slow_fast.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim_generic/rtl/prim_xor2.sv
hw/ip/prim_generic/rtl/prim_and2.sv
hw/ip/prim_generic/rtl/prim_buf.sv
hw/ip/prim_generic/rtl/prim_flop.sv
hw/ip/prim_generic/rtl/prim_ram_1p.sv
hw/ip/prim_generic/rtl/prim_flash_bank.sv
hw/ip/prim_generic/rtl/prim_xnor2.sv
hw/ip/prim_generic/rtl/prim_clock_gating.sv
hw/ip/prim_generic/rtl/prim_flash.sv
hw/ip/prim_generic/rtl/prim_flop_2sync.sv
rtl_wrapper/alert_handler_perip_tb.sv
