+incdir+hw
+incdir+hw/ip/csrng/rtl
+incdir+hw/ip/edn/rtl
+incdir+hw/ip/entropy_src/rtl
+incdir+hw/ip/flash_ctrl/rtl
+incdir+hw/ip/keymgr/rtl
+incdir+hw/ip/kmac/rtl
+incdir+hw/ip/lc_ctrl/rtl
+incdir+hw/ip/otp_ctrl/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/prim_generic/rtl
+incdir+hw/ip/rom_ctrl/rtl
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey/rtl
hw/ip/prim/rtl/prim_assert.sv
hw/ip/csrng/rtl/csrng_pkg.sv
hw/ip/csrng/rtl/csrng_reg_pkg.sv
hw/ip/edn/rtl/edn_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_pkg.sv
hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
hw/ip/keymgr/rtl/keymgr_pkg.sv
hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
hw/ip/kmac/rtl/kmac_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_cipher_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/rom_ctrl/rtl/rom_ctrl_pkg.sv
hw/ip/kmac/rtl/sha3_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_lfsr.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
hw/ip/prim/rtl/prim_sec_anchor_const.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_msb_extend.sv
hw/ip/prim/rtl/prim_buf.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_flop.sv
hw/ip/prim/rtl/prim_edn_req.sv
hw/ip/prim/rtl/prim_mubi4_sync.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_mubi4_sender.sv
hw/ip/prim/rtl/prim_flop_2sync.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
hw/ip/keymgr/rtl/keymgr_op_state_ctrl.sv
hw/ip/keymgr/rtl/keymgr_ctrl.sv
hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
hw/ip/keymgr/rtl/keymgr_kmac_if.sv
hw/ip/keymgr/rtl/keymgr.sv
hw/ip/keymgr/rtl/keymgr_cfg_en.sv
hw/ip/keymgr/rtl/keymgr_data_en_state.sv
hw/ip/keymgr/rtl/keymgr_err.sv
hw/ip/keymgr/rtl/keymgr_reg_top.sv
hw/ip/keymgr/rtl/keymgr_input_checks.sv
hw/ip/keymgr/rtl/keymgr_sideload_key.sv
hw/ip/prim_generic/rtl/prim_const_sec.sv
rtl_wrapper/keymgr_perip_tb.sv
