+incdir+hw
+incdir+hw/ip/csrng/rtl
+incdir+hw/ip/edn/rtl
+incdir+hw/ip/entropy_src/rtl
+incdir+hw/ip/keymgr/rtl
+incdir+hw/ip/lc_ctrl/rtl
+incdir+hw/ip/otp_ctrl/rtl
+incdir+hw/ip/otp_macro/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/pwrmgr/rtl
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey/ip_autogen/otp_ctrl/rtl
+incdir+hw/top_earlgrey/ip_autogen/pwrmgr/rtl
+incdir+hw/top_earlgrey/rtl
hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
hw/ip/kmac/rtl/kmac_pkg.sv
hw/ip/kmac/rtl/sha3_pkg.sv
hw/ip/prim/rtl/prim_assert.sv
hw/ip/csrng/rtl/csrng_pkg.sv
hw/ip/edn/rtl/edn_pkg.sv
hw/ip/entropy_src/rtl/entropy_src_pkg.sv
hw/ip/keymgr/rtl/keymgr_pkg.sv
hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv
hw/ip/keymgr_dpe/rtl/keymgr_dpe_pkg.sv
hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_top_specific_pkg.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
hw/ip/otp_macro/rtl/otp_macro_pkg.sv
hw/ip/otp_macro/rtl/otp_macro_reg_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_cipher_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_esc_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim/rtl/prim_ram_1p_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/top_earlgrey/rtl/top_racl_pkg.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_scrmbl.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_buf.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lci.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_kdi.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_ecc_reg.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_token_const.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_socket_1n.sv
hw/ip/tlul/rtl/tlul_fifo_sync.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_socket_m1.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_adapter_sram.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_sram_byte.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_edge_detector.sv
hw/ip/prim/rtl/prim_generic_flop_2sync.sv
hw/ip/prim/rtl/prim_lfsr.sv
hw/ip/prim/rtl/prim_generic_flop.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_secded_72_64_enc.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_alert_receiver.sv
hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_packer_fifo.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_buf.sv
hw/ip/prim/rtl/prim_rst_sync.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_arbiter_tree_dup.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_arbiter_fixed.sv
hw/ip/prim/rtl/prim_double_lfsr.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_present.sv
hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_mubi8_sender.sv
hw/ip/prim/rtl/prim_flop.sv
hw/ip/prim/rtl/prim_edn_req.sv
hw/ip/prim/rtl/prim_mubi4_sync.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_leading_one_ppc.sv
hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_secded_72_64_dec.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_lc_sender.sv
hw/ip/prim/rtl/prim_arbiter_tree.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_mubi4_sender.sv
hw/ip/prim/rtl/prim_flop_2sync.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/otp_macro/rtl/otp_macro_reg_top.sv
hw/ip/otp_macro/rtl/otp_macro.sv
rtl_wrapper/otp_ctrl_perip_tb.sv
