+incdir+hw
+incdir+hw/hw/ip/prim/rtl
+incdir+hw/hw/ip/prim_generic/rtl
+incdir+hw/ip/kmac/rtl
+incdir+hw/ip/lc_ctrl/rtl
+incdir+hw/ip/otp_ctrl/rtl
+incdir+hw/ip/otp_macro/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/prim_generic/rtl
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey
+incdir+hw/top_earlgrey/ip/ast/rtl
+incdir+hw/top_earlgrey/rtl
+incdir+hw/workspace/opentitan/hw/ip/prim/rtl
hw/ip/prim/rtl/prim_assert.sv
hw/ip/lc_ctrl/rtl/prim_assert.sv
hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
hw/top_earlgrey/dm_pkg.sv
hw/top_earlgrey/jtag_pkg.sv
hw/ip/kmac/rtl/kmac_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv
hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
hw/ip/otp_macro/rtl/otp_macro_pkg.sv
hw/ip/otp_macro/rtl/otp_macro_reg_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_esc_pkg.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/kmac/rtl/sha3_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/top_earlgrey/rtl/top_racl_pkg.sv
hw/hw/ip/prim/rtl/prim_buf.sv
hw/hw/ip/prim/rtl/prim_flop_2sync.sv
hw/hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_lc_sync.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/workspace/opentitan/hw/ip/prim/rtl/prim_lc_sender.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv
hw/ip/lc_ctrl/rtl/lc_ctrl.sv
hw/ip/lc_ctrl/rtl/prim_flop.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_dmi_reg_top.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
hw/ip/lc_ctrl/rtl/lc_ctrl_regs_reg_top.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_generic_flop.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_esc_receiver.sv
hw/ip/prim/rtl/prim_buf.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_flop.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_lc_sender.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_flop_2sync.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
hw/ip/prim_generic/rtl/prim_xnor2.sv
hw/ip/otp_macro/rtl/otp_macro_reg_top.sv
hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv
hw/ip/otp_macro/rtl/otp_macro.sv
rtl_wrapper/lc_perip_tb.sv
