+incdir+hw
+incdir+hw/hw
+incdir+hw/hw/ip
+incdir+hw/hw/ip/prim
+incdir+hw/hw/ip/prim_generic
+incdir+hw/hw/ip/prim_generic/rtl
+incdir+hw/hw/ip/prim/rtl
+incdir+hw/hw/ip/tlul
+incdir+hw/hw/ip/tlul/rtl
+incdir+hw/hw/top_earlgrey
+incdir+hw/hw/top_earlgrey/ip_autogen
+incdir+hw/hw/top_earlgrey/ip_autogen/gpio
+incdir+hw/hw/top_earlgrey/ip_autogen/gpio/rtl
+incdir+hw/hw/top_earlgrey/rtl
+incdir+hw/hw/top_earlgrey/rtl/autogen
+incdir+hw/ip
+incdir+hw/ip/gpio
+incdir+hw/ip/gpio/rtl
+incdir+hw/ip/prim
+incdir+hw/ip/prim_common
+incdir+hw/ip/prim_common/rtl
+incdir+hw/ip/prim/rtl
+incdir+hw/top_earlgrey
+incdir+hw/top_earlgrey/rtl
hw/hw/ip/tlul/rtl/tlul_pkg.sv
hw/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_pkg.sv
hw/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_pkg.sv
hw/hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv
hw/ip/prim_common/rtl/prim_alert_pkg.sv
hw/ip/prim_common/rtl/prim_mubi_pkg.sv
hw/ip/prim_common/rtl/prim_secded_pkg.sv
hw/ip/prim_common/rtl/prim_subreg_pkg.sv
hw/ip/prim_common/rtl/prim_util_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
hw/hw/ip/prim/rtl/prim_filter_ctr.sv
hw/hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/hw/ip/tlul/rtl/tlul_err.sv
hw/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_top.sv
hw/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio.sv
hw/ip/prim_common/rtl/prim_assert.sv
hw/ip/prim_common/rtl/prim_buf.sv
hw/ip/prim_common/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim_common/rtl/prim_flop_macros.sv
hw/ip/prim_common/rtl/prim_flop.sv
hw/ip/prim_common/rtl/prim_onehot_check.sv
hw/ip/prim_common/rtl/prim_reg_we_check.sv
hw/ip/prim_common/rtl/prim_secded_64_57_enc.sv
hw/ip/prim_common/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_flop_2sync.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_sec_anchor_buf.sv
hw/ip/prim/rtl/prim_sec_anchor_flop.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_subreg.sv
rtl_wrapper/gpio_perip_tb.sv
