+incdir+hw
+incdir+hw/ip
+incdir+hw/ip/mbx
+incdir+hw/ip/mbx/rtl
+incdir+hw/ip/prim
+incdir+hw/ip/prim/rtl
+incdir+hw/ip/prim_generic
+incdir+hw/ip/prim_generic/rtl
+incdir+hw/ip/tlul
+incdir+hw/ip/tlul/rtl
+incdir+hw/top_earlgrey
+incdir+hw/top_earlgrey/rtl
+incdir+rtl_wrapper
hw/ip/prim/rtl/prim_assert.sv
hw/ip/prim/rtl/prim_mubi_pkg.sv
hw/ip/prim/rtl/prim_secded_pkg.sv
hw/ip/prim/rtl/prim_util_pkg.sv
hw/ip/prim/rtl/prim_alert_pkg.sv
hw/ip/prim/rtl/prim_esc_pkg.sv
hw/top_earlgrey/rtl/top_pkg.sv
hw/top_earlgrey/rtl/top_racl_pkg.sv
hw/ip/tlul/rtl/tlul_pkg.sv
hw/ip/mbx/rtl/mbx_reg_pkg.sv
hw/ip/prim/rtl/prim_flop_macros.sv
hw/ip/prim/rtl/prim_flop.sv
hw/ip/prim/rtl/prim_generic_flop.sv
hw/ip/prim/rtl/prim_xnor2.sv
hw/ip/prim/rtl/prim_generic_flop_2sync.sv
hw/ip/prim/rtl/prim_flop_2sync.sv
hw/ip/prim/rtl/prim_buf.sv
hw/ip/prim/rtl/prim_rst_sync.sv
hw/ip/prim/rtl/prim_edge_detector.sv
hw/ip/prim/rtl/prim_slicer.sv
hw/ip/prim/rtl/prim_leading_one_ppc.sv
hw/ip/prim/rtl/prim_arbiter_ppc.sv
hw/ip/prim/rtl/prim_arbiter_tree.sv
hw/ip/prim/rtl/prim_arbiter_fixed.sv
hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
hw/ip/prim/rtl/prim_fifo_sync.sv
hw/ip/prim/rtl/prim_fifo_async.sv
hw/ip/prim/rtl/prim_sync_reqack.sv
hw/ip/prim/rtl/prim_sync_reqack_data.sv
hw/ip/prim/rtl/prim_count_pkg.sv
hw/ip/prim/rtl/prim_count.sv
hw/ip/prim/rtl/prim_onehot_check.sv
hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
hw/ip/prim/rtl/prim_subreg_pkg.sv
hw/ip/prim/rtl/prim_subreg_ext.sv
hw/ip/prim/rtl/prim_subreg_arb.sv
hw/ip/prim/rtl/prim_subreg.sv
hw/ip/prim/rtl/prim_subreg_shadow.sv
hw/ip/prim/rtl/prim_reg_we_check.sv
hw/ip/prim/rtl/prim_lc_sync.sv
hw/ip/prim/rtl/prim_lc_sender.sv
hw/ip/prim/rtl/prim_diff_decode.sv
hw/ip/prim/rtl/prim_alert_sender.sv
hw/ip/prim/rtl/prim_esc_receiver.sv
hw/ip/prim/rtl/prim_intr_hw.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
hw/ip/tlul/rtl/tlul_data_integ_enc.sv
hw/ip/tlul/rtl/tlul_data_integ_dec.sv
hw/ip/tlul/rtl/tlul_err.sv
hw/ip/tlul/rtl/tlul_adapter_reg.sv
hw/ip/tlul/rtl/tlul_adapter_sram.sv
hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
hw/ip/tlul/rtl/tlul_socket_m1.sv
hw/ip/tlul/rtl/tlul_socket_1n.sv
hw/ip/tlul/rtl/tlul_adapter_host.sv
hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
hw/ip/prim/rtl/prim_onehot_enc.sv
hw/ip/prim/rtl/prim_flop_en.sv
hw/ip/tlul/rtl/tlul_sram_byte.sv
hw/ip/mbx/rtl/mbx_sramrwarb.sv
hw/ip/mbx/rtl/mbx_imbx.sv
hw/ip/mbx/rtl/mbx_ombx.sv
hw/ip/mbx/rtl/mbx_hostif.sv
hw/ip/mbx/rtl/mbx_sysif.sv
hw/ip/mbx/rtl/mbx_fsm.sv
hw/ip/mbx/rtl/mbx_core_reg_top.sv
hw/ip/mbx/rtl/mbx_soc_reg_top.sv
hw/ip/mbx/rtl/mbx.sv
rtl_wrapper/mbx_perip_tb.sv
